### ISSUE TITLE
The project does not work as expected.

### ISSUE THREAD

**Issue by BasicPrimitives** [LukasBombach/tree-shakable-component-library#8]
OK

**Comment by LukasBombach** [comment]
Hey @BasicPrimitives I'm not quite sure what you are asking here, can you elaborate what you want from this issue titled "Fail!"?

**Comment by BasicPrimitives** [comment]
I am trying to build your project, but I don't see it to exclude "I MUST NOT BE HERE!"
I just see that I need to use ESM packages in order to get shakable library.
